Repository lisegmbh/fluxflow, pull requests merged in 2024-06, with the labels that each got.

#168 remove AnyOf filter aliases
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/filter/InFilter.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/inmemory/filter/InMemoryInFilter.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/query/filter/MongoInFilter.kt
Labels: 🛠️ refactoring

#170 Allow specifying a default MongoDB collection collation
  docs/spring/settings.md
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/MongoConfiguration.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/CreateCollectionsBootstrapAction.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/collation/CollationConfiguration.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/collation/CollationConfigurer.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/collation/CollationOptions.kt
Labels: 🌱 enhancement, 💾 persistence

#173 Allow specifying version for workflow elements - I - API Changes
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/StepDefinition.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/NoVersion.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/SimpleVersion.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/Version.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/VersionCompatibility.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/VersionWithCompatibility.kt
  library/core/api/src/test/kotlin/de/lise/fluxflow/api/versioning/SimpleVersionTest.kt
  library/core/api/src/test/kotlin/de/lise/fluxflow/api/versioning/VersionCompatibilityTest.kt
  library/core/api/src/test/kotlin/de/lise/fluxflow/api/versioning/VersionWithCompatibilityTest.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepServiceImpl.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/StepActivationServiceTest.kt
  library/core/persistence/src/main/kotlin/de/lise/fluxflow/persistence/step/StepData.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/ReflectedStatefulStepDefinition.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/Step.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/StepDefinitionBuilder.kt
  library/core/stereotyped/src/test/kotlin/de/lise/fluxflow/stereotyped/unwrapping/UnwrapServiceImplTest.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/step/StepDocument.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/step/StepMongoPersistence.kt
Labels: 🌱 enhancement, 💾 persistence, 🔗 api

#174 Allow specifying version for workflow elements - II - Obtaining a manually set version from a @Version annotation
  CHANGELOG.md
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/StepActivationServiceTest.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/StepDefinitionBuilder.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/versioning/Version.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/versioning/VersionBuilder.kt
  library/core/stereotyped/src/test/kotlin/de/lise/fluxflow/stereotyped/step/StepDefinitionBuilderIT.kt
  library/core/stereotyped/src/test/kotlin/de/lise/fluxflow/stereotyped/step/StepDefinitionBuilderTest.kt
  library/core/stereotyped/src/test/kotlin/de/lise/fluxflow/stereotyped/versioning/VersionBuilderTest.kt
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/configuration/BasicConfiguration.kt
Labels: 📖 documentation, 🌱 enhancement

#176 Allow custom collations when ensuring indexes
  CHANGELOG.md
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/MongoBootstrapAction.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/PersistentIndex.kt
Labels: 🌱 enhancement, 💾 persistence

#175 Allow migrating workflow elements - [I] - Migrate type maps and add initial migration tooling
  docs/spring/settings.md
  library/core/migration/build.gradle.kts
  library/core/migration/src/main/kotlin/de/lise/fluxflow/migration/ExecutableMigration.kt
  library/core/migration/src/main/kotlin/de/lise/fluxflow/migration/Migration.kt
  library/core/migration/src/main/kotlin/de/lise/fluxflow/migration/MigrationError.kt
  library/core/migration/src/main/kotlin/de/lise/fluxflow/migration/MigrationKey.kt
  library/core/migration/src/main/kotlin/de/lise/fluxflow/migration/MigrationProvider.kt
  library/core/migration/src/main/kotlin/de/lise/fluxflow/migration/MigrationService.kt
  library/core/migration/src/main/kotlin/de/lise/fluxflow/migration/MigrationServiceImpl.kt
  library/core/migration/src/main/kotlin/de/lise/fluxflow/migration/NoOpExecutableMigration.kt
  library/core/migration/src/main/kotlin/de/lise/fluxflow/migration/UnsupportedMigrationException.kt
  library/core/migration/src/main/kotlin/de/lise/fluxflow/migration/common/TypeRenameMigration.kt
  library/core/migration/src/test/kotlin/de/lise/fluxflow/migration/MigrationServiceImplTest.kt
  library/core/persistence/src/main/kotlin/de/lise/fluxflow/persistence/migration/DuplicateMigrationException.kt
  library/core/persistence/src/main/kotlin/de/lise/fluxflow/persistence/migration/MigrationData.kt
  library/core/persistence/src/main/kotlin/de/lise/fluxflow/persistence/migration/MigrationPersistence.kt
  library/core/test-persistence/build.gradle.kts
  library/core/test-persistence/src/main/kotlin/de/lise/fluxflow/test/persistence/migration/InMemoryMigrationProvider.kt
  library/core/test-persistence/src/main/kotlin/de/lise/fluxflow/test/persistence/migration/MigrationTestPersistence.kt
  library/settings.gradle.kts
  library/springboot/springboot-in-memory-persistence/src/main/kotlin/de/lise/fluxflow/springboot/InMemoryPersistenceConfiguration.kt
  library/springboot/springboot-mongo/build.gradle.kts
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/MongoConfiguration.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/CreateIndexesBootstrapAction.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/MigrateDataTypesMapBootstrapAction.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/MigrateJobParameterTypesMapBootstrapAction.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/MigrateMetadataTypesMapBootstrapAction.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/MigrateToTypeRecordsBootstrapAction.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/PartialFailureAction.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/CollectionType.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/NullType.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/SimpleType.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/TypeSpec.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/record/CollectionTypeRecord.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/record/JvmTypeMapping.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/record/JvmTypeRecord.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/record/NullTypeRecord.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/record/RecordContext.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/record/TypeName.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/record/TypeRecord.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/record/TypeRecordEntry.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/record/TypeReference.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/generic/record/TypedRecords.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/job/JobDocument.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/migration/MigrationDocument.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/migration/MigrationMongoPersistence.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/migration/MigrationRepository.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/migration/MongoMigrationProvider.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/migration/common/MongoExecutableTypeRenameMigration.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/step/StepDocument.kt
Labels: 🌱 enhancement, 💾 persistence, 🔗 api

#177 Alow migrating workflow elements - II - Documentation
  docs/migrations/unreleased.md
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/MongoConfiguration.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/MigrateToTypeRecordsBootstrapAction.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/migration/common/MongoExecutableTypeRenameMigration.kt
  library/springboot/springboot/build.gradle.kts
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/configuration/BasicConfiguration.kt
  mkdocs.yml
Labels: 📖 documentation, 🌱 enhancement

#178 Increase SNAPSHOT version and add changelog entry
  CHANGELOG.md
  library/build.gradle.kts
Labels: 📖 documentation

#180 Persist versioned step definitions - [I] - Implement persistence layer
  library/core/persistence/src/main/kotlin/de/lise/fluxflow/persistence/step/definition/DataDefinitionData.kt
  library/core/persistence/src/main/kotlin/de/lise/fluxflow/persistence/step/definition/StepDefinitionData.kt
  library/core/persistence/src/main/kotlin/de/lise/fluxflow/persistence/step/definition/StepDefinitionPersistence.kt
  library/core/test-persistence/src/main/kotlin/de/lise/fluxflow/test/persistence/step/definition/StepDefinitionTestPersistence.kt
  library/springboot/springboot-in-memory-persistence/src/main/kotlin/de/lise/fluxflow/springboot/InMemoryPersistenceConfiguration.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/MongoConfiguration.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/step/definition/DataDefinitionDocument.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/step/definition/StepDefinitionDocument.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/step/definition/StepDefinitionMongoPersistence.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/step/definition/StepDefinitionRepository.kt
Labels: 🌱 enhancement, 💾 persistence

#181 Persist versioned step definitions - [II] - Implement workflow logic to persist step definitions
  docs/spring/settings.md
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/NoOpVersionRecorder.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/VersionRecorder.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepServiceImpl.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/definition/StepDefinitionService.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/definition/StepDefinitionVersionRecorder.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/definition/StepDefinitionServiceTest.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/definition/StepDefinitionVersionRecorderTest.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/CreateIndexesBootstrapAction.kt
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/configuration/BasicConfiguration.kt
Labels: 🌱 enhancement

#182 Persist versioned step definitions - III - Enforce version compatibility when activating steps
  docs/spring/settings.md
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/RestoredStep.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/VersionCompatibility.kt
  library/core/api/src/test/kotlin/de/lise/fluxflow/api/versioning/VersionCompatibilityTest.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepActivation.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepActivationException.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepActivationServiceImpl.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/data/RestoredData.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/data/RestoredDataDefinition.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/definition/RestoredStepDefinition.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/definition/RestoredStepImpl.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/StepActivationServiceTest.kt
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/configuration/BasicConfiguration.kt
Labels: 🌱 enhancement

#185 Persist versioned step definitions - [IV] - Use stored step definition to restore step on occurring errors
  docs/spring/settings.md
  library/build.gradle.kts
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/stateful/StepActivationException.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/SimpleVersion.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/Version.kt
  library/core/api/src/test/kotlin/de/lise/fluxflow/api/versioning/SimpleVersionTest.kt
  library/core/api/src/test/kotlin/de/lise/fluxflow/api/versioning/VersionTest.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/DefaultStepActivationService.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/RestoringStepActivationService.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepActivation.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/definition/StepDefinitionService.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/DefaultStepActivationServiceTest.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/RestoringStepActivationServiceTest.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/data/ReflectedModifiableData.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/data/SetPropertyFailedException.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/data/StepDataAssignmentException.kt
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/configuration/BasicConfiguration.kt
Labels: 🌱 enhancement

#186 Fix OutOfMemoryException occurring when migrating too many documents
  docs/migrations/unreleased.md
  library/build.gradle.kts
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/ActionBuffer.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/MigrateToTypeRecordsBootstrapAction.kt
Labels: 🐞 bug, 💾 persistence

#187 Document versioning feature
  CHANGELOG.md
  docs/features/automation.md
  docs/features/injection.md
  docs/features/queries.md
  docs/features/validation.md
  docs/features/versioning.md
  mkdocs.yml
Labels: 📖 documentation

#189 Automatic step migration - [I] - Add version property to the step API object
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/Step.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/StepDefinition.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/StepImpl.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/stateful/StatefulStepImpl.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/DefaultStepActivationService.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/RestoringStepActivationService.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepServiceImpl.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/definition/RestoredStepDefinition.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/definition/RestoredStepImpl.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/RestoringStepActivationServiceTest.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/ReflectedStatefulStepDefinition.kt
Labels: 🌱 enhancement, 🔗 api

#190 Automatic step migration - [II] - Query by version
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/query/filter/StepFilter.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/query/filter/VersionFilter.kt
  library/core/persistence/src/main/kotlin/de/lise/fluxflow/persistence/step/query/filter/StepDataFilter.kt
  library/core/test-persistence/src/main/kotlin/de/lise/fluxflow/test/persistence/step/query/filter/StepTestFilter.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/step/StepMongoPersistence.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/step/query/filter/StepDocumentFilter.kt
Labels: 🌱 enhancement, 💾 persistence

#191 Automatic step migration - [III] - Upgrade compatible version when persisting changes to old steps
  docs/spring/settings.md
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepServiceImpl.kt
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/configuration/BasicConfiguration.kt
Labels: 🌱 enhancement
