Repository lisegmbh/fluxflow, pull requests merged in 2024-07, with the labels that each got.

#192 Automatic step migration - [IV] - Allow querying for steps independent from their parent workflow
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/StepService.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepServiceImpl.kt
  library/core/persistence/src/main/kotlin/de/lise/fluxflow/persistence/step/StepPersistence.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/filter/Filter.kt
  library/core/test-persistence/src/main/kotlin/de/lise/fluxflow/test/persistence/step/StepTestPersistence.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/step/StepMongoPersistence.kt
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/configuration/BasicConfiguration.kt
Labels: 🌱 enhancement, 💾 persistence

#198 Allow passing additional information when updating step data
  CHANGELOG.md
  docs/steps.md
  library/build.gradle.kts
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/event/FlowEvent.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/stateful/data/StepDataService.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/event/action/ActionEvent.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/event/step/StepCreatedEvent.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/event/step/StepUpdatedEvent.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/event/step/data/StepDataEvent.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/event/workflow/BeforeWorkflowUpdateEvent.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/event/workflow/WorkflowCreatedEvent.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/event/workflow/WorkflowDeletedEvent.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/event/workflow/WorkflowUpdatedEvent.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/data/StepDataServiceImpl.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/data/StepDataServiceImplTest.kt
Labels: 📖 documentation, 🌱 enhancement, 🔗 api

#203 Group jackson updates into one pull request
  .github/dependabot.yml
Labels: dependencies

#204 remove UnwrapService and StepExtensions
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepExtensions.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/unwrapping/IllegalUnwrapException.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/unwrapping/UnwrapService.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/unwrapping/UnwrapServiceImpl.kt
  library/core/stereotyped/src/test/kotlin/de/lise/fluxflow/stereotyped/unwrapping/UnwrapServiceImplTest.kt
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/configuration/BasicConfiguration.kt
Labels: 🛠️ refactoring

#210 Move .bind extension function to stereotyped module
  library/build.gradle.kts
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/data/StepDataServiceImplTest.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/StepExtensions.kt
Labels: 🌱 enhancement

#217 Extract compatibility check out of version
  docs/spring/settings.md
  docs/style.css
  library/build.gradle.kts
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/CompatibilityConfiguration.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/CompatibilityTester.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/DefaultCompatibilityTester.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/NoVersion.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/SimpleVersion.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/Version.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/versioning/VersionWithCompatibility.kt
  library/core/api/src/test/kotlin/de/lise/fluxflow/api/versioning/DefaultCompatibilityTesterTest.kt
  library/core/api/src/test/kotlin/de/lise/fluxflow/api/versioning/SimpleVersionTest.kt
  library/core/api/src/test/kotlin/de/lise/fluxflow/api/versioning/VersionWithCompatibilityTest.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/DefaultStepActivationService.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepServiceImpl.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/DefaultStepActivationServiceTest.kt
  library/core/stereotyped/src/test/kotlin/de/lise/fluxflow/stereotyped/versioning/VersionBuilderTest.kt
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/configuration/BasicConfiguration.kt
Labels: 🛠️ refactoring
