Repository lisegmbh/fluxflow, pull requests merged in 2024-03, with the labels that each got.

#107 Link changelog within documentation and readme and add missing changelog entries
  CHANGELOG.md
  README.md
  mkdocs.yml
Labels: 📖 documentation

#108 Document the WorkflowService with KDoc
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/workflow/WorkflowService.kt
Labels: 📖 documentation, 🔗 api

#111 Throw an exception if dependency resolution fails for other reasons than the dependency being missing
  CHANGELOG.md
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/ioc/SpringIocProvider.kt
  library/springboot/springboot/src/test/kotlin/de/lise/fluxflow/springboot/ioc/SpringIocProviderTest.kt
  library/springboot/springboot/src/test/kotlin/de/lise/fluxflow/springboot/ioc/testservices/BaseService.kt
  library/springboot/springboot/src/test/kotlin/de/lise/fluxflow/springboot/ioc/testservices/BaseServiceImpl.kt
  library/springboot/springboot/src/test/kotlin/de/lise/fluxflow/springboot/ioc/testservices/DuplicateService.kt
  library/springboot/springboot/src/test/kotlin/de/lise/fluxflow/springboot/ioc/testservices/DuplicateServiceImpl1.kt
  library/springboot/springboot/src/test/kotlin/de/lise/fluxflow/springboot/ioc/testservices/DuplicateServiceImpl2.kt
  library/springboot/springboot/src/test/kotlin/de/lise/fluxflow/springboot/ioc/testservices/ExtendingService.kt
  library/springboot/springboot/src/test/kotlin/de/lise/fluxflow/springboot/ioc/testservices/ExtendingServiceImpl.kt
  library/springboot/springboot/src/test/kotlin/de/lise/fluxflow/springboot/ioc/testservices/SpringIocProviderTestService.kt
Labels: 🐞 bug, 🔀 core workflow

#112 Refactor workflow service interface
  CHANGELOG.md
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/workflow/WorkflowQueryService.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/workflow/WorkflowRemovalService.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/workflow/WorkflowService.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/continuation/ContinuationService.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/job/JobSchedulingCallback.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/workflow/WorkflowQueryServiceImpl.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/workflow/WorkflowRemovalServiceImpl.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/workflow/WorkflowServiceImpl.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/workflow/WorkflowStarterServiceImpl.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/FluxFlowIT.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/continuation/ContinuationServiceTest.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/job/JobSchedulingCallbackTest.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/automation/StepAutomationIT.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/workflow/WorkflowIT.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/workflow/WorkflowITTestModel.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/workflow/WorkflowListenerIT.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/workflow/WorkflowRemovalServiceImplTest.kt
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/configuration/BasicConfiguration.kt
Labels: 🛠️ refactoring, 🔗 api

#113 Fix spelling mistake in SECURITY.md
  SECURITY.md
Labels: 📖 documentation

#116 Fix failing activation for custom step kinds
  CHANGELOG.md
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/StepConfigurationException.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepActivation.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepActivationServiceImpl.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepTypeResolver.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/StepTypeResolverImpl.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/IntegrationTestConfig.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/StepActivationServiceTest.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/StepIT.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/TestStepWithCustomKind.kt
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/activation/StepKindMapBuilder.kt
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/configuration/BasicConfiguration.kt
Labels: 🐞 bug, 💾 persistence

#117 add step data modification policy
  CHANGELOG.md
  docs/steps.md
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/stateful/data/DataDefinition.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/stateful/data/ModificationPolicy.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/step/data/StepDataServiceImpl.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/data/StepDataServiceImplTest.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/data/Data.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/data/DataDefinitionBuilder.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/data/ReflectedDataDefinition.kt
Labels: 🌱 enhancement, 🔀 core workflow, 🔗 api

#118 Add Oemer to contributor list
  .github/CODEOWNERS
  README.md
Labels: 📖 documentation

#123 Add metadata feature supporting step data
  CHANGELOG.md
  docs/steps.md
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/step/stateful/data/DataDefinition.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/StepActivationServiceTest.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/data/DataIT.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/data/DataTestStep.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/step/data/DataTestStepAnnotation.kt
  library/core/reflection/src/main/kotlin/de/lise/fluxflow/reflection/property/KPropertyExtensions.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/metadata/MetadataBuilder.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/data/DataDefinitionBuilder.kt
  library/core/stereotyped/src/main/kotlin/de/lise/fluxflow/stereotyped/step/data/ReflectedDataDefinition.kt
  library/core/stereotyped/src/test/kotlin/de/lise/fluxflow/stereotyped/step/data/DataDefinitionBuilderTest.kt
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/configuration/BasicConfiguration.kt
Labels: 🌱 enhancement, 🔗 api

#137 Enhance sort functionality to handle nullable properties (#135)
  CHANGELOG.md
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/inmemory/sort/InMemoryPropertySort.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/sort/Sort.kt
  library/core/query/src/test/kotlin/de.lise.fluxflow.query/sort/InMemoryPropertySortTest.kt
Labels: 🌱 enhancement

#139 Add a sort that assumes the elements to be sorted are of a given subtype
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/workflow/query/sort/WorkflowModelSort.kt
  library/core/persistence/src/main/kotlin/de/lise/fluxflow/persistence/workflow/query/sort/WorkflowDataModelSort.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/inmemory/sort/InMemorySort.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/sort/DefaultSort.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/sort/OfTypeSort.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/sort/PropertySort.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/sort/Sort.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/sort/ValueSort.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/query/sort/MongoSort.kt
Labels: 🌱 enhancement, 🔗 api
