Repository lisegmbh/fluxflow, pull requests merged in 2025-03, with the labels that each got.

#278 Add indexes on job collection
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/bootstrapping/CreateIndexesBootstrapAction.kt
Labels: 🌱 enhancement, 💾 persistence

#279 Use JUnit BOM for dependency version management and update to 5.12.0
  library/build.gradle.kts
  library/core/engine/build.gradle.kts
Labels: dependencies

#277 Add `not` filter to negate a filter
  CHANGELOG.md
  library/build.gradle.kts
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/filter/Filter.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/filter/NotFilter.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/inmemory/filter/InMemoryFilter.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/inmemory/filter/InMemoryNotFilter.kt
  library/core/query/src/test/kotlin/de/lise/fluxflow/query/filter/InMemoryNotFilterTest.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/query/filter/MongoFilter.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/query/filter/MongoNotFilter.kt
  library/springboot/springboot-mongo/src/test/kotlin/de/lise/fluxflow/mongo/query/filter/MongoFilterTest.kt
  library/springboot/springboot-mongo/src/test/kotlin/de/lise/fluxflow/mongo/query/filter/MongoNotFilterTest.kt
Labels: 🌱 enhancement

#286 Add `elemMatch` filter
  CHANGELOG.md
  library/build.gradle.kts
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/filter/ElemMatchFilter.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/filter/Filter.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/inmemory/filter/InMemoryElemMatchFilter.kt
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/inmemory/filter/InMemoryFilter.kt
  library/core/query/src/test/kotlin/de/lise/fluxflow/query/filter/InMemoryElemMatchFilterTest.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/query/filter/MongoElemMatchFilter.kt
  library/springboot/springboot-mongo/src/main/kotlin/de/lise/fluxflow/mongo/query/filter/MongoFilter.kt
  library/springboot/springboot-mongo/src/test/kotlin/de/lise/fluxflow/mongo/query/filter/MongoElemMatchFilterTest.kt
  library/springboot/springboot-mongo/src/test/kotlin/de/lise/fluxflow/mongo/query/filter/MongoFilterTest.kt
Labels: 🌱 enhancement
