Repository lisegmbh/fluxflow, pull requests merged in 2025-04, with the labels that each got.

#287 add duplicateJob function
  CHANGELOG.md
  library/build.gradle.kts
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/job/JobService.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/job/JobServiceImpl.kt
Labels: 🌱 enhancement

#285 Add metadata for workflow
  CHANGELOG.md
  docs/workflow/model.md
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/workflow/Workflow.kt
  library/core/api/src/main/kotlin/de/lise/fluxflow/api/workflow/WorkflowDefinition.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/workflow/WorkflowActivationServiceImpl.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/workflow/WorkflowDefinitionImpl.kt
  library/core/engine/src/main/kotlin/de/lise/fluxflow/engine/workflow/WorkflowImpl.kt
  library/core/engine/src/test/kotlin/de/lise/fluxflow/engine/workflow/WorkflowMetadataIT.kt
  library/springboot/springboot/src/main/kotlin/de/lise/fluxflow/springboot/configuration/BasicConfiguration.kt
Labels: 🌱 enhancement, 🔗 api

#291 fix: prevent StackOverflowError caused by infinite ImMemoryAndFilter constructor chain
  CHANGELOG.md
  library/build.gradle.kts
  library/core/query/src/main/kotlin/de.lise.fluxflow.query/inmemory/filter/InMemoryAndFilter.kt
  library/core/query/src/test/kotlin/de/lise/fluxflow/query/filter/InMemoryAndFilterTest.kt
Labels: 🐞 bug
